<?php

declare(strict_types=1);

namespace Nowo\BreadcrumbKitBundle\Command;

use Doctrine\DBAL\Schema\AbstractSchemaManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\SchemaTool;
use Nowo\BreadcrumbKitBundle\Entity\BreadcrumbCollection;
use Nowo\BreadcrumbKitBundle\Entity\BreadcrumbItem;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

/**
 * Generates a Doctrine migration for breadcrumb tables (connection + table prefix from config).
 */
#[AsCommand(
    name: 'nowo_breadcrumb_kit:generate-migration',
    description: 'Generate a migration to create/update breadcrumb tables (uses config connection and table_prefix)',
)]
final class GenerateBreadcrumbKitMigrationCommand extends Command
{
    private const MIGRATION_TEMPLATE = <<<'PHP'
<?php

declare(strict_types=1);

namespace %s;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Breadcrumb Kit tables (collection + item).
 * Generated by nowo_breadcrumb_kit:generate-migration.
 * Connection: %s | Table prefix: %s
 */
final class Version%s_CreateBreadcrumbKitTablesByConfiguration extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create/update dashboard_breadcrumb_* tables (prefix: %s)';
    }

    public function up(Schema $schema): void
    {
%s
    }

    public function down(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();
        $this->addSql($platform->getDropTableSQL('%s'));
        $this->addSql($platform->getDropTableSQL('%s'));
    }
}

PHP;

    public function __construct(
        private readonly EntityManagerInterface $em,
        private readonly string $connectionName,
        private readonly string $tablePrefix,
        ?string $name = null,
    ) {
        parent::__construct($name);
    }

    protected function configure(): void
    {
        $this
            ->addOption('path', 'p', InputOption::VALUE_REQUIRED, 'Directory where to write the migration file', 'migrations')
            ->addOption('namespace', null, InputOption::VALUE_REQUIRED, 'PHP namespace for the migration class', 'DoctrineMigrations')
            ->addOption('update', null, InputOption::VALUE_NONE, 'Generate ALTER statements for new columns on existing tables')
            ->addOption('dump', null, InputOption::VALUE_NONE, 'Only output the SQL without writing a file');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $metaCollection = $this->em->getClassMetadata(BreadcrumbCollection::class);
        $metaItem = $this->em->getClassMetadata(BreadcrumbItem::class);
        $schemaTool = new SchemaTool($this->em);
        $createSql = $schemaTool->getCreateSchemaSql([$metaCollection, $metaItem]);

        $collectionTable = $metaCollection->getTableName();
        $itemTable = $metaItem->getTableName();

        $sql = $createSql;
        if ((bool) $input->getOption('update')) {
            $conn = $this->em->getConnection();
            $platform = $conn->getDatabasePlatform();
            /** @phpstan-ignore function.alreadyNarrowedType */
            $sm = method_exists($conn, 'createSchemaManager') ? $conn->createSchemaManager() : null;
            $alterSql = [];
            if ($sm instanceof AbstractSchemaManager && $sm->tablesExist([$itemTable])) {
                $table = $sm->introspectTable($itemTable);
                $quoted = $platform->quoteSingleIdentifier($itemTable);
                if (!$table->hasColumn('path_pattern')) {
                    $alterSql[] = \sprintf('ALTER TABLE %s ADD path_pattern VARCHAR(512) DEFAULT NULL', $quoted);
                }
                if (!$table->hasColumn('match_attributes')) {
                    $alterSql[] = \sprintf('ALTER TABLE %s ADD match_attributes JSON DEFAULT NULL', $quoted);
                }
            }
            $sql = $alterSql;
        }

        if ($input->getOption('dump')) {
            foreach ($sql as $statement) {
                $io->writeln($statement.';');
            }
            $io->note('Use the same Doctrine connection as nowo_breadcrumb_kit.doctrine.connection when different from default.');

            return Command::SUCCESS;
        }

        if ([] === $sql) {
            $io->success('Nothing to write (schema already up to date for --update, or empty SQL).');

            return Command::SUCCESS;
        }

        $path = (string) $input->getOption('path');
        $namespace = trim((string) $input->getOption('namespace'), '\\');
        $version = date('YmdHis');
        $className = 'Version'.$version.'_CreateBreadcrumbKitTablesByConfiguration';

        $sqlLines = array_map(
            static fn (string $statement): string => '        $this->addSql('.var_export($statement, true).');',
            $sql,
        );
        $sqlBlock = implode("\n", $sqlLines);

        $prefixDisplay = '' === $this->tablePrefix ? '(none)' : $this->tablePrefix;
        $content = \sprintf(
            self::MIGRATION_TEMPLATE,
            $namespace,
            $this->connectionName,
            $prefixDisplay,
            $version,
            $prefixDisplay,
            $sqlBlock,
            $itemTable,
            $collectionTable,
        );

        $filesystem = new Filesystem();
        $targetDir = $path;
        if (!$filesystem->isAbsolutePath($path)) {
            $targetDir = getcwd().\DIRECTORY_SEPARATOR.$path;
        }
        if (!is_dir($targetDir)) {
            $filesystem->mkdir($targetDir);
        }
        $file = $targetDir.\DIRECTORY_SEPARATOR.$className.'.php';
        $filesystem->dumpFile($file, $content);

        $io->success(\sprintf('Migration written to %s', $file));
        $io->text([
            'Connection: '.$this->connectionName,
            'Table prefix: '.$prefixDisplay,
            'Tables: '.$collectionTable.', '.$itemTable,
        ]);
        if ('default' !== $this->connectionName) {
            $io->note(\sprintf('Run: php bin/console doctrine:migrations:migrate --conn=%s', $this->connectionName));
        }

        return Command::SUCCESS;
    }
}
