<?php

declare(strict_types=1);

namespace Nowo\BreadcrumbKitBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * YAML defaults; trail definitions live in the database (collections + items).
 */
final class Configuration implements ConfigurationInterface
{
    public const ALIAS = 'nowo_breadcrumb_kit';

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        $root = $treeBuilder->getRootNode();

        $root
            ->children()
                ->scalarNode('project')
                    ->info('Optional project id when several apps share one DB.')
                    ->defaultNull()
                ->end()
                ->arrayNode('doctrine')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('connection')->defaultValue('default')->end()
                        ->scalarNode('table_prefix')
                            ->info('Prefix prepended to table names (dashboard_breadcrumb_collection, dashboard_breadcrumb_item). Empty = no prefix.')
                            ->defaultValue('')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('cache')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('ttl')->min(0)->defaultValue(60)->end()
                        ->scalarNode('pool')
                            ->info('PSR-6 pool service id, e.g. cache.app. Empty disables item-list cache.')
                            ->defaultValue('cache.app')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('locales')
                    ->scalarPrototype()->end()
                    ->defaultValue([])
                ->end()
                ->scalarNode('default_locale')->defaultNull()->end()
                ->scalarNode('default_collection')
                    ->info('Collection code used when none is passed to Twig/helpers.')
                    ->defaultValue('default')
                ->end()
                ->arrayNode('presentation')
                    ->info('Default trail presentation; collection homeIcon and responsiveConfig can override per collection.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('home_icon')
                            ->info('Fallback home/root icon (HTML, emoji, or app-specific token) when the collection homeIcon is empty.')
                            ->defaultNull()
                        ->end()
                        ->booleanNode('home_icon_replaces_label')
                            ->info('When true and a home icon is set, the first crumb shows the icon instead of its text label (label stays in aria-label).')
                            ->defaultTrue()
                        ->end()
                        ->booleanNode('hide_when_single_root')
                            ->info('When true, hides the trail on pages where the only crumb is the root item and it is the current page (typical home).')
                            ->defaultFalse()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('dashboard')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                            ->info('Registers CRUD controllers and forms; import bundle routing with path_prefix (see docs).')
                        ->end()
                        ->scalarNode('path_prefix')
                            ->defaultValue('/breadcrumb-kit-admin')
                            ->info('URL prefix for dashboard routes (leading slash, no trailing slash). Use the same value when importing routing in your app.')
                        ->end()
                        ->scalarNode('layout_template')
                            ->defaultValue('@NowoBreadcrumbKitBundle/dashboard/layout.html.twig')
                            ->info('Twig layout extended by dashboard pages (override in app like DashboardMenuBundle).')
                        ->end()
                        ->integerNode('import_max_bytes')
                            ->defaultValue(2_097_152)
                            ->min(1024)
                            ->info('Max JSON upload size for dashboard import (default 2 MiB).')
                        ->end()
                        ->arrayNode('pagination')
                            ->info('Pagination for the collections list in the dashboard.')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultValue(true)
                                ->end()
                                ->integerNode('per_page')
                                    ->min(1)
                                    ->max(500)
                                    ->defaultValue(20)
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('modals')
                            ->info('Modal dialog size per type: normal (default), lg, or xl (Bootstrap 5).')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('collection_form')
                                    ->defaultValue('lg')
                                    ->validate()
                                        ->ifNotInArray(['normal', 'lg', 'xl'])
                                        ->thenInvalid('Must be normal, lg, or xl.')
                                    ->end()
                                ->end()
                                ->scalarNode('item_form')
                                    ->defaultValue('lg')
                                    ->validate()
                                        ->ifNotInArray(['normal', 'lg', 'xl'])
                                        ->thenInvalid('Must be normal, lg, or xl.')
                                    ->end()
                                ->end()
                                ->scalarNode('import')
                                    ->defaultValue('normal')
                                    ->validate()
                                        ->ifNotInArray(['normal', 'lg', 'xl'])
                                        ->thenInvalid('Must be normal, lg, or xl.')
                                    ->end()
                                ->end()
                                ->scalarNode('delete')
                                    ->defaultValue('normal')
                                    ->validate()
                                        ->ifNotInArray(['normal', 'lg', 'xl'])
                                        ->thenInvalid('Must be normal, lg, or xl.')
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('inline_edit')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('query_param')
                            ->defaultNull()
                            ->info('Query parameter name; when present and truthy (1, true, yes, on), the default breadcrumb template may show an edit control if the collection enables a checker and the checker allows access.')
                        ->end()
                        ->arrayNode('access_services')
                            ->info('Logical key => service id implementing BreadcrumbInlineEditAccessCheckerInterface. Collections choose one key in the dashboard.')
                            ->useAttributeAsKey('key')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
