parameters:
    container.dumper.inline_class_loader: false

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\DataFixtures\:
        resource: '../src/DataFixtures/'

    App\Breadcrumb\:
        resource: '../src/Breadcrumb/'
